Functional 404
NebulaServices/3kh0 pull request #21
Opened 2023-09-18 23:01 UTC by sudo-njr

I fixed the cdn, the games and images should load now.

2nd commit: 404 error should work now,
- Matched navigation bar and footer
- Formatted HTML
- Put quotes around the title stats.
- Made the stats for nerds font smaller, (Looks better)
### BEFORE
![before](https://github.com/NebulaServices/3kh0/assets/131909495/dfd9ec17-456c-446a-973c-9ea6caa34998)

### AFTER
![after](https://github.com/NebulaServices/3kh0/assets/131909495/38bc7e75-20d0-4baf-a58a-d83f85fb4d49)

2023-10-18 02:12 UTC, 3kh0 requested changes
Keep the CDNs.json as is

2023-10-18 03:16 UTC, sudo-njr commented
Okay, I'll do it like in 16 hours because of school

2023-10-18 22:32 UTC, 3kh0 approved these changes

2024-07-05 17:56 UTC, nathanielrz commented
Are all these contributors not contributing no more because it's been 8 months.

2024-08-24 15:47 UTC, closed without merging